
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.nio.file.Files;
import java.nio.file.Paths;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daniel
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public tela() {  
	
        initComponents();
	tabela.removeAll();
	lista_bancos.setEnabled(false);
	mostrar_bancos.setEnabled(false);
	espacio_algoritmo.setEnabled(false);
	executar.setEnabled(false);
	lista_tabelas.setEnabled(false);
	mostrar_tabela.setEnabled(false);
	mostrar_metadados.setEnabled(false);
	tabela.setEnabled(false);
	abrir_conexao();

	
	
	
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                conteiner_tabela = new javax.swing.JScrollPane();
                tabela = new javax.swing.JTable();
                banco = new javax.swing.JLabel();
                usuario = new javax.swing.JLabel();
                senha = new javax.swing.JLabel();
                usuario_entrada = new javax.swing.JTextField();
                boton_conectar = new javax.swing.JButton();
                cointeiner_query = new javax.swing.JScrollPane();
                espacio_algoritmo = new javax.swing.JTextArea();
                executar = new javax.swing.JButton();
                lista_tabelas = new javax.swing.JComboBox<>();
                mostrar_tabela = new javax.swing.JButton();
                lista_bancos = new javax.swing.JComboBox<>();
                mostrar_bancos = new javax.swing.JButton();
                senha_entrada = new javax.swing.JPasswordField();
                mostrar_metadados = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                endereco = new javax.swing.JLabel();
                endereco_entrada = new javax.swing.JComboBox<>();
                banco_entrada = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                tabela.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] { },
                        new String [] {}) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
                tabela.setRowHeight(50);
                conteiner_tabela.setViewportView(tabela);

                banco.setText("banco");

                usuario.setText("usuario");

                senha.setText("senha");

                usuario_entrada.setColumns(10);

                boton_conectar.setText("conectar");
                boton_conectar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                boton_conectarActionPerformed(evt);
                        }
                });

                espacio_algoritmo.setColumns(20);
                espacio_algoritmo.setRows(5);
                cointeiner_query.setViewportView(espacio_algoritmo);

                executar.setText("executar query");
                executar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                executarActionPerformed(evt);
                        }
                });

                mostrar_tabela.setText("mostrar tabela");
                mostrar_tabela.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mostrar_tabelaActionPerformed(evt);
                        }
                });

                lista_bancos.setEditable(true);

                mostrar_bancos.setText("selecionar banco");
                mostrar_bancos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mostrar_bancosActionPerformed(evt);
                        }
                });

                senha_entrada.setColumns(10);

                mostrar_metadados.setText("mostrar estrura");
                mostrar_metadados.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mostrar_metadadosActionPerformed(evt);
                        }
                });

                jLabel1.setText("selecione uma tabela");

                endereco.setText("endereço");

                endereco_entrada.setEditable(true);
                endereco_entrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "localhost" }));

                banco_entrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mysql", "postgresql" }));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                                .addComponent(mostrar_bancos)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lista_bancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(executar)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(mostrar_tabela)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(mostrar_metadados)))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lista_tabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel1)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(boton_conectar)
                                                                        .addComponent(banco_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(banco))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(usuario)
                                                                        .addComponent(usuario_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(senha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(senha))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(endereco)
                                                                        .addComponent(endereco_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cointeiner_query)
                                                        .addComponent(conteiner_tabela))))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(banco)
                                        .addComponent(usuario)
                                        .addComponent(senha)
                                        .addComponent(endereco))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usuario_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(senha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endereco_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(banco_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(boton_conectar)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(mostrar_bancos)
                                                        .addComponent(lista_bancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(cointeiner_query, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(executar))
                                        .addComponent(jLabel1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mostrar_metadados)
                                        .addComponent(mostrar_tabela)
                                        .addComponent(lista_tabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(conteiner_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void boton_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_conectarActionPerformed
        
            // TODO add your handling code here:   
            tabela.removeAll();
            prepara_banco("show databases","");
            
            var campos = intro_banco_de_dados.pega_linhas();
            lista_bancos.removeAllItems();
            campos.forEach(aux -> {
                lista_bancos.addItem(aux);
            });
	  
	lista_bancos.setEnabled(true);
	mostrar_bancos.setEnabled(true);
	salvar_conexao();
	
	    
    }//GEN-LAST:event_boton_conectarActionPerformed

    private void abrir_conexao(){

	    try {
		    usuario_entrada.setText(new String(Files.readAllBytes(Paths.get("usuario.txt"))));
		    banco_entrada.setSelectedItem(new String(Files.readAllBytes(Paths.get("banco.txt"))));
		    
		    endereco_entrada.setSelectedItem(new String(Files.readAllBytes(Paths.get("endereco.txt"))));
		    senha_entrada.setText(Files.readString(Paths.get("senha.txt")));
		    System.out.println(Files.readString(Paths.get("senha.txt")));
	    } catch (IOException ignored) {
	    }
    }
    
    private void salvar_conexao() {
	    try {
		    var str_usuario = new PrintWriter("usuario.txt", "UTF-8");
		    var str_senha = new PrintWriter("senha.txt", "UTF-8");
		    var str_endereco = new PrintWriter("endereco.txt", "UTF-8");
		    var str_banco = new PrintWriter("banco.txt", "UTF-8");
		    str_usuario.print(usuario_entrada.getText());
		    str_usuario.close();
		    str_senha.print(senha_entrada.getPassword());
		    str_senha.close();
		    str_endereco.print(endereco_entrada.getSelectedItem());
		    str_endereco.close();
		    str_banco.print(banco_entrada.getSelectedItem());
		    str_banco.close();
		    str_usuario.close();
	    } catch (FileNotFoundException | UnsupportedEncodingException ignored) {
	    }
    }
    private void mostrar_bancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_bancosActionPerformed
        // TODO add your handling code here:
        var  str_banco = lista_bancos.getSelectedItem()+"";
	prepara_banco("show tables", str_banco);
        var campos = intro_banco_de_dados.pega_linhas();
        lista_tabelas.removeAllItems();
        campos.forEach(aux -> {
                lista_tabelas.addItem(aux);
        });
	espacio_algoritmo.setEnabled(true);
	executar.setEnabled(true);
	lista_tabelas.setEnabled(true);
	mostrar_tabela.setEnabled(true);
	mostrar_metadados.setEnabled(true);
        
    }//GEN-LAST:event_mostrar_bancosActionPerformed

    private void prepara_banco(String query,String banco_dados){
        var str_banco_tipo = banco_entrada.getSelectedItem()+"";
        var str_usuario = usuario_entrada.getText();
        var str_senha = new String(senha_entrada.getPassword());
	var str_endereco = endereco_entrada.getSelectedItem()+"";
        intro_banco_de_dados.carrega_driver(str_banco_tipo,banco_dados,str_endereco,str_usuario,str_senha);
        intro_banco_de_dados.carrega_codigo(query);
    }
        
    private void executarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarActionPerformed
        // TODO add your handling code here:
	tabela.setEnabled(true);
        var query = espacio_algoritmo.getText()+" limit 20";
	mostrar_tabela(query);
    }//GEN-LAST:event_executarActionPerformed

    private void mostrar_tabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_tabelaActionPerformed
        // TODO add your handling code here:
	tabela.setEnabled(true);
	var query = "select * from "+lista_tabelas.getSelectedItem()+" limit 20";
	intro_banco_de_dados.carrega_codigo(query);
	mostrar_tabela(query);
	
    }//GEN-LAST:event_mostrar_tabelaActionPerformed

        private void mostrar_metadadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_metadadosActionPerformed
                // TODO add your handling code here:
		var query = "select *"
			+ " from INFORMATION_SCHEMA.COLUMNS "
			+ "where table_name ='"+lista_tabelas.getSelectedItem()+"' limit 20";
			intro_banco_de_dados.carrega_codigo(query);
		mostrar_tabela(query);
        }//GEN-LAST:event_mostrar_metadadosActionPerformed

    private void mostrar_tabela(String query){
	intro_banco_de_dados.carrega_codigo(query);
        var objeto = new Object[20][];
        for(int i = 0; i < 20 ;i++)
        {		
		var linha = intro_banco_de_dados.pega_colunas();
		objeto[i] = linha.toArray();       
        }

        tabela.setModel(new javax.swing.table.DefaultTableModel(
                objeto,intro_banco_de_dados.nome_colunas().stream().toArray()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
	    //</editor-fold>
	    //</editor-fold>
	    
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
		new tela().setVisible(true);
	});
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel banco;
        private javax.swing.JComboBox<String> banco_entrada;
        private javax.swing.JButton boton_conectar;
        private javax.swing.JScrollPane cointeiner_query;
        private javax.swing.JScrollPane conteiner_tabela;
        private javax.swing.JLabel endereco;
        private javax.swing.JComboBox<String> endereco_entrada;
        private javax.swing.JTextArea espacio_algoritmo;
        private javax.swing.JButton executar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JComboBox<String> lista_bancos;
        private javax.swing.JComboBox<String> lista_tabelas;
        private javax.swing.JButton mostrar_bancos;
        private javax.swing.JButton mostrar_metadados;
        private javax.swing.JButton mostrar_tabela;
        private javax.swing.JLabel senha;
        private javax.swing.JPasswordField senha_entrada;
        private javax.swing.JTable tabela;
        private javax.swing.JLabel usuario;
        private javax.swing.JTextField usuario_entrada;
        // End of variables declaration//GEN-END:variables
}
