
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daniel
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {    
        initComponents();
        intro_banco_de_dados.carrega_driver();
        intro_banco_de_dados.adicionar_coluna();
        intro_banco_de_dados.set_nomes_arquivos();
        intro_banco_de_dados.adiciona_fotos();
        intro_banco_de_dados.carrega_banco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_ultimo = new javax.swing.JButton();
        boton_inicio = new javax.swing.JButton();
        boton_proximo = new javax.swing.JButton();
        boton_anterior = new javax.swing.JButton();
        jLabel_nome = new javax.swing.JLabel();
        JTextField_nome = new javax.swing.JTextField();
        jLabel_foto = new javax.swing.JLabel();
        jLabel_departamento = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jTextField_departamento = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boton_ultimo.setText("ultimo");
        boton_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ultimoActionPerformed(evt);
            }
        });

        boton_inicio.setText("inicio");
        boton_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_inicioActionPerformed(evt);
            }
        });

        boton_proximo.setText("proximo");
        boton_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_proximoActionPerformed(evt);
            }
        });

        boton_anterior.setText("anterior");
        boton_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_anteriorActionPerformed(evt);
            }
        });

        jLabel_nome.setText("nome");

        JTextField_nome.setEditable(false);

        jLabel_foto.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel_fotoComponentAdded(evt);
            }
        });

        jLabel_departamento.setText("departamento");

        jLabel_id.setText("id");

        jTextField_departamento.setEditable(false);

        jTextField_id.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(boton_inicio))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel_nome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(boton_anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_proximo)
                .addGap(36, 36, 36)
                .addComponent(boton_ultimo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_departamento)
                            .addComponent(jLabel_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_departamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(JTextField_nome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_id)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(JTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_departamento)
                    .addComponent(jTextField_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_id)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_ultimo)
                    .addComponent(boton_inicio)
                    .addComponent(boton_proximo)
                    .addComponent(boton_anterior))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostra_info()
    {
        if(intro_banco_de_dados.pega_string("name") == null)
        {
        } else {
            JTextField_nome.setText(intro_banco_de_dados.pega_string("name"));
            jTextField_id.setText(intro_banco_de_dados.pega_string("id"));
            jTextField_departamento.setText(intro_banco_de_dados.pega_string("dept_name"));
            jLabel_foto.setIcon(intro_banco_de_dados.pega_icone());
        }

    }
 
    
    private void boton_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_anteriorActionPerformed
        intro_banco_de_dados.anterior();
        mostra_info();
    }//GEN-LAST:event_boton_anteriorActionPerformed

    private void boton_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_proximoActionPerformed
        intro_banco_de_dados.proximo();
        mostra_info();
    }//GEN-LAST:event_boton_proximoActionPerformed

    private void boton_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_inicioActionPerformed
        intro_banco_de_dados.inicio();
        mostra_info();
        
    }//GEN-LAST:event_boton_inicioActionPerformed

    private void boton_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ultimoActionPerformed
        intro_banco_de_dados.ultimo();
        mostra_info();
    }//GEN-LAST:event_boton_ultimoActionPerformed

    private void jLabel_fotoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel_fotoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_fotoComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextField_nome;
    private javax.swing.JButton boton_anterior;
    private javax.swing.JButton boton_inicio;
    private javax.swing.JButton boton_proximo;
    private javax.swing.JButton boton_ultimo;
    private javax.swing.JLabel jLabel_departamento;
    private javax.swing.JLabel jLabel_foto;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JTextField jTextField_departamento;
    private javax.swing.JTextField jTextField_id;
    // End of variables declaration//GEN-END:variables
}
